name: Playwright Tests
on:
  push:
    branches: [ main, release ]
  pull_request:
    branches: [ main, release ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23.4  # Update to match our Go version

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Create .env file
      run: echo "${{ secrets.ENV_FILE_FOR_PLAYWRIGHT_TESTS }}" > .env

    - name: Start Go server
      run: |
        go run cmd/main.go > server.log 2>&1 &
        echo $! > server.pid  # Save the PID of the server

    - name: Wait for server to be ready
      run: |
        for i in {1..20}; do
          if curl -s http://localhost:8080/login > /dev/null; then
            echo "Server is up"
            exit 0
          fi
          echo "Waiting for server..."
          sleep 1
        done
        echo "Server did not start in time"
        cat server.log
        exit 1

    - name: Print server logs if failed
      if: failure()
      run: cat server.log

    # Delete old auth state (if any)
    - name: Remove old auth state
      run: rm -f playwright/.auth/user.json

    # Generate fresh storage state
    - name: Generate fresh Playwright auth state
      run: npx playwright test tests/auth.setup.spec.ts

    # Run all other Playwright tests
    - name: Run Playwright tests
      run: npx playwright test --grep-invert "@auth-setup"

    - name: Stop Go server
      if: always()  # Ensure this runs even if tests fail
      run: |
        kill $(cat server.pid) || true
        rm server.pid

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
